version: '3'
services:
  mysql:
    build:
      context: ./mysql
    volumes:
      - "~/docker/dev/mysql/:/var/lib/mysql/"
    #    restart: always
    privileged: true

  webapp:
    build:
      context: ./webapp
    links:
      - mongodb-server
      - echo
      - redis
    volumes:
      - "../../:/var/www/html/"
      - "./webapp/files/php.conf:/etc/httpd/conf.d/php.conf"
      - "./webapp/files/httpd.conf:/etc/httpd/conf/httpd.conf"
      - "./webapp/files/composer_rsa:/root/.ssh/id_rsa"
    #    restart: always
    extra_hosts:
      - "test:192.168.0.7"
    privileged: true

  echo:
    build:
      context: ./webapp
    links:
      - redis
    volumes:
      - "../../:/var/www/html/"
      - "./webapp/files/php.conf:/etc/httpd/conf.d/php.conf"
      - "./webapp/files/httpd.conf:/etc/httpd/conf/httpd.conf"
      - "./webapp/files/composer_rsa:/root/.ssh/id_rsa"
  #    restart: always
  #    extra_hosts:
  #      - "echo-test:192.168.0.9"
  #    privileged: true

  yacron-server:
    build:
      context: ./webapp
    volumes:
      - "../../:/var/www/html/"
      - "./yacron/init-cron.yaml:/etc/init-cron.yaml"
    privileged: true
    command: /usr/local/bin/yacron -c /etc/init-cron.yaml
    #restart: always

  mongodb-server:
    image: "mongo:latest"
    volumes:
      - "~/docker/dev/mongodb/:/data/db/"
  #    restart: always

  supervisord:
    build:
      context: ./webapp
    volumes:
      - "../../:/var/www/html/"
      - "./supervisord/files/supervisord.conf:/etc/supervisord.conf"
    #    restart: always
    privileged: true
    command: supervisord -n

  elasticsearch-server:
    build:
      context: ./elasticsearch
    volumes:
      - "../elasticsearch-7.3.2:/usr/local/elasticsearch-7.3.2"
    #    restart: always
    privileged: true
  #    ports:
  #     - 9200:9200

  redis:
    build:
      context: ./redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
#    restart: always
