version: '3'
services:
  proxy:
    image: "jwilder/nginx-proxy:0.7.0"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx-proxy.conf:/etc/nginx/sites-enabled/reverse-proxy.conf:ro"

  mysql:
    build:
      context: ./mysql
    volumes:
      - "~/docker/dev/mysql/:/var/lib/mysql/"
    restart: always
    privileged: true

  webapp:
    build:
      context: ./webapp
    links:
      - mongodb-server
#     - echo
#     - redis
    volumes:
      - "../../:/var/www/html/"
      - "./webapp/files/php.conf:/etc/httpd/conf.d/php.conf"
      - "./webapp/files/httpd.conf:/etc/httpd/conf/httpd.conf"
    environment:
      VIRTUAL_HOST: birdboard.imusabah.com
    restart: always
    privileged: true

# echo:
#   build:
#     context: ./webapp
#   links:
#     - redis
#   volumes:
#     - "../../:/var/www/html/"
#     - "./webapp/files/php.conf:/etc/httpd/conf.d/php.conf"
#     - "./webapp/files/httpd.conf:/etc/httpd/conf/httpd.conf"
#    restart: always
#    privileged: true

  yacron-server:
    build:
      context: ./webapp
    volumes:
      - "../../:/var/www/html/"
      - "./yacron/init-cron.yaml:/etc/init-cron.yaml"
    privileged: true
    command: /usr/local/bin/yacron -c /etc/init-cron.yaml
    #restart: always

  mongodb-server:
    image: "mongo:latest"
    volumes:
      - "~/docker/dev/mongodb/:/data/db/"
    restart: always

  supervisord:
    build:
      context: ./webapp
    volumes:
      - "../../:/var/www/html/"
      - "./supervisord/files/supervisord.conf:/etc/supervisord.conf"
    restart: always
    privileged: true
    command: supervisord -n

# elasticsearch-server:
#   build:
#     context: ./elasticsearch
#   volumes:
#     - "../elasticsearch-7.3.2:/usr/local/elasticsearch-7.3.2"
#   restart: always
#   privileged: true

# redis:
#   build:
#     context: ./redis
#   volumes:
#     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
#  restart: always
