FROM nginx
RUN apt update && apt-get install vim
#COPY nginx.conf /etc/nginx/nginx.conf
#RUN apk update && apk add bash
#COPY /etc/nginx/conf.d/test.config /etc/nginx/conf.d/
#left its continer path ===> right its machin path
